public class OOPLecture {
    public static void main(String[] args) {

    }
    //PILLARS OF OOP: ABSTRACTION, ENCAPSULATION, INHERITANCE, POLYMORPHISM
    // EG. REMOTE CONTROL FOR ABSTRACTION, DOOR HANDLES/LOCKS - SIMPLIFIES THE COMPLEXITY OF SOMETHING
    // EG. get TMDBMovies() vs tmbd.getMovies() vs tmbd.base = base url for the API - PROCESS OF WRAPPING DATA AND FX INTO A SINGLE UNIT
    //EG. DOM MANIPULATION LIKE INNERHTML, INHERITANCE = (DRY - DON'T REPEAT YOURSELF) AND IS ABOUT SAYING THIS CLASS
}
